import { MockListing } from "@/types/listing";

export const MOCK_LISTINGS: MockListing[] = [
  {
    id: "1",
    slug: "apartament-3-camere-centru-sibiu",
    title: "Apartament 3 camere, Centrul Istoric",
    type: "APARTMENT",
    transactionType: "SALE",
    status: "ACTIVE",
    price: 142000,
    currency: "EUR",
    area: 78,
    rooms: 3,
    bathrooms: 1,
    floor: 3,
    totalFloors: 4,
    address: "Str. Nicolae Bălcescu 12",
    neighborhood: "Centrul Istoric",
    city: "Sibiu",
    latitude: 45.7983,
    longitude: 24.1498,
    pricePerSqm: 1820,
    yearBuilt: 1975,
    parking: false,
    furnished: true,
    features: ["Vedere spre centru", "Renovate complet", "Parchet"],
    energyClass: "C",
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600",
    agentName: "Andrei Popescu",
    agentImage: "https://i.pravatar.cc/100?img=12",
    agencyName: "Imobiliare Transilvania",
    featured: true,
  },
  {
    id: "2",
    slug: "casa-4-camere-tilisca-sibiu",
    title: "Casă individuală 4 camere, Tilișca",
    type: "HOUSE",
    transactionType: "SALE",
    status: "ACTIVE",
    price: 215000,
    currency: "EUR",
    area: 145,
    rooms: 4,
    bathrooms: 2,
    floor: 0,
    totalFloors: 2,
    address: "Str. Tilișca 45",
    neighborhood: "Tilișca",
    city: "Sibiu",
    latitude: 45.7765,
    longitude: 24.1612,
    pricePerSqm: 1483,
    yearBuilt: 2018,
    parking: true,
    furnished: false,
    features: ["Grădină 400mp", "Garaj", "Terasă", "Panouri solare"],
    energyClass: "A",
    imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600",
    agentName: "Maria Ionescu",
    agentImage: "https://i.pravatar.cc/100?img=25",
    agencyName: "Premium Real Estate SB",
    featured: true,
  },
  {
    id: "3",
    slug: "studio-turnisor-sibiu-chirie",
    title: "Studio modern, Turnisor",
    type: "STUDIO",
    transactionType: "RENT",
    status: "ACTIVE",
    price: 380,
    currency: "EUR",
    area: 38,
    rooms: 1,
    bathrooms: 1,
    floor: 2,
    totalFloors: 8,
    address: "Bd. Victoriei 78",
    neighborhood: "Turnisor",
    city: "Sibiu",
    latitude: 45.8045,
    longitude: 24.1389,
    pricePerSqm: 10,
    yearBuilt: 2022,
    parking: false,
    furnished: true,
    features: ["AC", "Interfon video", "Loc parcare inclus"],
    energyClass: "A+",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600",
    agentName: "Lucian Dăncilă",
    agentImage: "https://i.pravatar.cc/100?img=8",
    agencyName: "Sibiu Rentals",
    featured: false,
  },
  {
    id: "4",
    slug: "apartament-2-camere-vasile-aaron",
    title: "Apartament 2 camere, Vasile Aaron",
    type: "APARTMENT",
    transactionType: "SALE",
    status: "ACTIVE",
    price: 89000,
    currency: "EUR",
    area: 54,
    rooms: 2,
    bathrooms: 1,
    floor: 1,
    totalFloors: 4,
    address: "Str. Vasile Aaron 23",
    neighborhood: "Vasile Aaron",
    city: "Sibiu",
    latitude: 45.7892,
    longitude: 24.1601,
    pricePerSqm: 1648,
    yearBuilt: 1982,
    parking: false,
    furnished: false,
    features: ["Balcon", "Pivniță", "Izolat exterior"],
    energyClass: "D",
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600",
    agentName: "Elena Costea",
    agentImage: "https://i.pravatar.cc/100?img=47",
    agencyName: "Imobiliare Transilvania",
    featured: false,
  },
  {
    id: "5",
    slug: "penthouse-vedere-cetate-sibiu",
    title: "Penthouse cu vedere la Cetate",
    type: "APARTMENT",
    transactionType: "SALE",
    status: "ACTIVE",
    price: 340000,
    currency: "EUR",
    area: 180,
    rooms: 5,
    bathrooms: 3,
    floor: 7,
    totalFloors: 7,
    address: "Str. Mitropoliei 8",
    neighborhood: "Centrul Istoric",
    city: "Sibiu",
    latitude: 45.7931,
    longitude: 24.1523,
    pricePerSqm: 1889,
    yearBuilt: 2020,
    parking: true,
    furnished: true,
    features: ["Terasă 80mp", "Vedere panoramică", "Lift", "Boxa", "Sistem smart home"],
    energyClass: "A",
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600",
    agentName: "Andrei Popescu",
    agentImage: "https://i.pravatar.cc/100?img=12",
    agencyName: "Premium Real Estate SB",
    featured: true,
  },
];
